import RecoilContextProvider from "@/lib/RecoilContextProvider";
import { NextUIProvider } from "@nextui-org/react";
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hitch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <head>
        <script
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
        ></script>
      </head>
      <body className={inter.className} >
        <RecoilContextProvider >
          <NextUIProvider>
            <Theme>

              <main>
                {children}
              </main>
            </Theme>
          </NextUIProvider>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
